import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import vm from 'node:vm';
const root = '_site';
const read = p => fs.readFileSync(path.join(root,p),'utf8');
const home = read('index.html');
const source = fs.readFileSync('dist/index.html','utf8');
const publisher = /<script async src="https:\/\/pagead2[^>]+><\/script>/;
assert.equal(home.match(publisher)?.[0], source.match(publisher)?.[0], 'AdSense verification code changed');
assert.equal(read('ads.txt'), fs.readFileSync('dist/ads.txt','utf8'));
assert.deepEqual([...home.matchAll(/<meta name="google-site-verification"[^>]*>/g)].map(m=>m[0]), [...source.matchAll(/<meta name="google-site-verification"[^>]*>/g)].map(m=>m[0]));
const scriptPaths=[...home.matchAll(/<script[^>]+src="(\/[^"]+)"/g)].map(m=>m[1]);
assert.equal(scriptPaths.length,1,'Catalog and application should load in one bundled request');
const packed = read(scriptPaths[0]);
const catalogCode = packed.slice(0,packed.indexOf('\n;'));
const context=vm.createContext({window:{}});vm.runInContext(catalogCode,context);
const novels=context.window.NOVELS;
const escape = value => String(value ?? '').replace(/[&<>]/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
const policyLinks = [...source.match(/<footer[\s\S]*?<\/footer>/)[0].matchAll(/href="([^"]+)"/g)].map(m=>m[1]);
const hydration = packed.split('\n;')[1];
const header = {outerHTML:''}, footer = {outerHTML:''};
const base = {setAttribute:(name,value)=>{assert.equal(name,'href');assert.equal(value,'/');}};
const preload = {dataset:{staticChapter:novels[0].id,chapterNumber:'1'},querySelectorAll:()=>[{textContent:'A & B < C'}]};
context.document = {head:{insertAdjacentHTML:()=>{}},querySelector:selector=>selector==='[data-static-header]'?header:selector==='[data-static-footer]'?footer:selector==='base'?base:selector==='[data-static-chapter]'?preload:null};
vm.runInContext(hydration,context);
assert.equal(header.outerHTML,source.match(/<header\b[\s\S]*?<\/header>/)[0],'Reader controls must be restored before application startup');
assert.equal(footer.outerHTML, source.match(/<footer\b[\s\S]*?<\/footer>/)[0], 'Full policy footer must be restored before startup');
assert.equal(novels[0].chapters[0].paragraphs[0],'A & B < C');
assert.equal(novels[0].chapters[0].lazy,false,'Direct readers must hydrate the existing text');
context.document = {querySelector:()=>null};
assert.doesNotThrow(()=>vm.runInContext(hydration,context),'Shared runtime must also work on discovery pages');
let expected=0;
for(const n of novels){
 const prefix='novel/'+encodeURIComponent(n.id)+'/';
 const files=fs.readdirSync(path.join(root,prefix)).filter(f=>f.startsWith('chapter-'));
 assert.equal(files.length,n.chapters.length,n.id+' lost chapter pages');expected+=files.length;
 const samples=[1,Math.ceil(n.chapters.length/2),n.chapters.length];
 for(const number of samples){
  const url='/'+prefix+'chapter-'+number+'/';const text=read(url+'index.html');
  assert(text.includes('href="https://novelhaven.top'+url+'"'),'Wrong canonical');
  assert.match(text,/<meta name="robots" content="index,follow/);
  assert(text.includes('data-static-chapter="'+n.id+'"'),'Wrong chapter content');
  assert(text.includes('data-chapter-number="'+number+'"'),'Wrong reading position');
  assert.doesNotMatch(text,/Loading chapter…/);
  assert.equal(text.match(publisher)?.[0],source.match(publisher)?.[0]);
  assert.equal(text.match(/<meta name="google-site-verification"[^>]*>/)?.[0],source.match(/<meta name="google-site-verification"[^>]*>/)?.[0]);
  for(const href of policyLinks) assert(footer.outerHTML.includes('href="'+href+'"'),'Missing policy link '+href);
  for(const href of ['/privacy.html','/privacy-choices.html','/terms.html','/copyright.html','/contact.html']) assert(text.includes('href="'+href+'"'),'Missing static policy '+href);
  assert(text.includes('<base href="/'+prefix+'">'),'Static relative navigation uses wrong base');
  const config=n.lazyChunks,part=Math.ceil(number/config.capacity);
  const chunk=vm.createContext({window:{}});
  vm.runInContext(fs.readFileSync('dist/'+config.prefix+String(part).padStart(2,'0')+'.js','utf8'),chunk);
  const raw=chunk.window[config.global][(number-1)%config.capacity];
  const paragraphs=raw.paragraphs.map(p=>'<p>'+escape(p)).join('');
  assert(text.includes('data-chapter-number="'+number+'">'+paragraphs+'</div>'),'Static chapter text differs from source');
  for(const [,asset] of text.matchAll(/(?:src|href)="(\/assets\/[^"#?]*)/g)) assert(fs.existsSync(path.join(root,asset)),'Missing reader asset '+asset);
 }
}
for(const url of ['latest-releases','latest-novels','completed','browse','finder','reading-desk','library']) assert(fs.existsSync(path.join(root,url,'index.html')));
for(const name of ['privacy.html','privacy-choices.html','content-licensing.html','copyright.html','privacy-controls.js']) assert.equal(read(name),fs.readFileSync('dist/'+name,'utf8'),'Policy changed unexpectedly');
for(const [,url] of home.matchAll(/(?:src|href)="(\/[^"#?]*)[^\"]*"/g)) {
 const full=path.join(root,decodeURIComponent(url));
 assert(fs.existsSync(full)||fs.existsSync(full+'.html'),'Missing homepage link/asset '+url);
}
assert.match(read('sitemap.xml'),/<sitemapindex/);
assert.match(read('404.html'),/noindex,follow/);
assert.doesNotMatch(read('404.html'),/pagead2\.googlesyndication/);
assert(!fs.existsSync(path.join(root,'data'))),'Duplicated chapter payload';
console.log(`Verified ${novels.length} novels, ${expected} chapter pages, public routes, bundled assets, sitemaps, and unchanged AdSense/trust files.`);
