import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';
const context={window:{}};vm.createContext(context);
const dataFiles=fs.readdirSync('dist/data').filter(f=>/^gallery-chapters-\d+\.js$/.test(f)).sort();
assert.equal(dataFiles.length,10,'Expected 10 gallery chapter data files');
for(const file of dataFiles)vm.runInContext(fs.readFileSync(`dist/data/${file}`,'utf8'),context);
vm.runInContext(fs.readFileSync('dist/licensed-gallery.js','utf8'),context);
const novels=context.window.NOVELS;
assert(Array.isArray(novels));
assert.equal(novels.length,1,'NovelNest should contain only one published novel');
const n=novels[0];
assert.equal(n.id,'got-a-gallery-in-the-wild');
assert.equal(n.chapters.length,170,'Expected 170 chapters');
for(const field of ['title','author','genre','status','synopsis'])assert(typeof n[field]==='string'&&n[field].trim(),`missing ${field}`);
assert(Array.isArray(n.tags)&&n.tags.length>0);
assert(fs.existsSync('dist/'+n.cover),'missing cover');
assert(n.license?.type&&n.license?.note,'document publishing permission');
for(const c of n.chapters){assert(c.title&&c.paragraphs?.length);assert(c.paragraphs.every(p=>typeof p==='string'&&p.trim()));}
for(const asset of ['app.js','licensed-gallery.js','styles.css'])assert(fs.existsSync('dist/'+asset));
new vm.Script(fs.readFileSync('dist/app.js','utf8'));
const index=fs.readFileSync('dist/index.html','utf8');
assert(!index.includes('catalog.js'),'Old sample catalog must not be loaded');
assert(!index.includes('licensed-ui.js'),'Legacy UI patch must not be loaded');
assert(!fs.existsSync('dist/downloads/got-a-gallery-in-the-wild.epub'),'EPUB download should not be published');
console.log(`Validated ${novels.length} licensed novel and ${n.chapters.length} chapters.`);
